### ISSUE TITLE
Char.Items changes

### ISSUE THREAD

**Issue by Sephem** [keneanung/GMCPAdditions#5]
It seems there is a new field added to Char.Items called icon.

Not sure what it is exactly, but seems to be a more accurate attribute. 

It looks like it was added to be used to display icons on the HTML client maybe?

**Comment by keneanung** [comment]
:+1: I good catch!

I agree that it might be to show an icon for the item in the HTML5 client, but there is nothing that would handle it currently.

Sarapis showed off some screensots of the nex version of te client as well as hinted at additional GMCP content, so hat version might have it.

If you agree, I will add a short blob to the Char.Items listing but won't put much detail into it until the new client is out.

**Comment by Sephem** [comment]
Yip add it for now, even if you just say for future use.
