### ISSUE TITLE
Previously unseen GMCP message

### ISSUE THREAD

**Issue by kevnuke** [keneanung/GMCPAdditions#6]
Just wondering if you've ever seen this message before. I saw it with raw GMCP debugging on and don't know which module enabled it.

`Client.Map { "url": "http://www.achaea.com/maps/map.xml" }`

**Comment by keneanung** [comment]
Ha, right! It's a message we (as in the Mudlet team) cooked up a while ago with MUD server administrators to help with the discovery of server provided maps. I forgot to add it here.
